### ISSUE TITLE
Files related to visualizing Camera trajectory and 3D point cloud in RViz

### ISSUE THREAD

**Issue by Mechazo11** [ISAE-PNX/SaDVIO#4]
Hi @bartoszptak 

Thank you very much for publicly releasing SaDVIO. I too am working on a SLAM framework and am interested to learn how you visualized the camera pose and 3D map points (landmarks). Can you direct me to the files that are related to publishing these geometric data to Rviz?

With best regards,
@Mechazo11

**Comment by cdebeunne** [comment]
Hi @Mechazo11! 

All the files related to visualization are located in the [/ros](https://github.com/ISAE-PNX/SaDVIO/tree/main/ros) folder. In particular, the file [rosVisualizer.h](https://github.com/ISAE-PNX/SaDVIO/blob/main/ros/src/rosVisualizer.h) contains all the functions that publish VIO output on ROS2. The published message can then be displayed on RVIZ. I use `geometry_msgs::msg::PoseStamped` to publish the current pose and `visualization_msgs::msg::Marker` for point clouds and trajectories.

Kind regards
César

**Comment by Mechazo11** [comment]
Thank you very much @cdebeunne appreciate the help. As far as I know, this code stack is the only one outside of ORB SLAM (from ROS 1 era) that uses Rviz to visualize camera pose and point cloud data.
