### ISSUE TITLE
The version of the dependency library in ROS1

### ISSUE THREAD

**Issue by DoongLi** [ISAE-PNX/SaDVIO#5]
Hi, nice work! I try to run it, and I saw the code uses OpenCV, CERES, Eigen, yaml-cpp, and PCL, can you tell us which version you use in this code?

**Comment by cdebeunne** [comment]
Hi @DoongLi ! It works with OpenCV 4.2, CERES 2.0 (at least), Eigen 3.4.0, yaml-cpp 0.8.0 and PCL 1.10.0. But I think you can try with older or newer versions, it should be compliant. Tell me if you have any issues at compilation with your setup

**Comment by DoongLi** [comment]
Thx a lot, and I will try it.
